// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConfigureGitAndXcode(arg1:string,arg2:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function GetCurrentGitConfig():Promise<Record<string, string>>;

export function LoadProfiles():Promise<Array<main.Profile>>;

export function SaveProfile(arg1:main.Profile):Promise<void>;

export function SetGitProfile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function VerifyPIN(arg1:string,arg2:string):Promise<void>;
