// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigureGitAndXcode(arg1, arg2) {
  return window['go']['main']['App']['ConfigureGitAndXcode'](arg1, arg2);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function GetCurrentGitConfig() {
  return window['go']['main']['App']['GetCurrentGitConfig']();
}

export function LoadProfiles() {
  return window['go']['main']['App']['LoadProfiles']();
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function SetGitProfile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetGitProfile'](arg1, arg2, arg3, arg4);
}

export function VerifyPIN(arg1, arg2) {
  return window['go']['main']['App']['VerifyPIN'](arg1, arg2);
}
